//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveApplication.LeaveRequestForm {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class LeaveRequestForm {
        
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl dateTimeStartDate;
        
        protected global::System.Web.UI.WebControls.CheckBox rbFromHalfday;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnhalfday;
        
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl dateTimeEndDate;
        
        protected global::System.Web.UI.WebControls.CheckBox rbToHalfday;
        
        protected global::System.Web.UI.WebControls.Panel pnlHalfDay;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Selecteddates;
        
        protected global::System.Web.UI.WebControls.DropDownList lstboxOptionalLeaves;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl optinalDates;
        
        protected global::System.Web.UI.WebControls.Panel PnloptinalDates;
        
        protected global::System.Web.UI.WebControls.Label lblEmpID;
        
        protected global::System.Web.UI.WebControls.Label lblDesgination;
        
        protected global::System.Web.UI.WebControls.Label lblDepartment;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlTypeofLeave;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblDuration;
        
        protected global::System.Web.UI.WebControls.HiddenField txtDuration;
        
        protected global::System.Web.UI.WebControls.TextBox txtPurpose;
        
        protected global::System.Web.UI.WebControls.TextBox ddlReportingTo;
        
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        
        protected global::System.Web.UI.WebControls.Button btnReset;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnCurrentUsername;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnReportingTo;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnCurrentYear;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnEmployeeType;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnHolidayList;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnFnclStarts;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnFnclEnds;
        
        protected global::System.Web.UI.WebControls.Label lblError;
        
        public static implicit operator global::System.Web.UI.TemplateControl(LeaveRequestForm target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControldateTimeStartDate() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.dateTimeStartDate = @__ctrl;
            @__ctrl.ID = "dateTimeStartDate";
            @__ctrl.DateOnly = true;
            @__ctrl.LocaleId = 1033;
            @__ctrl.OnValueChangeClientScript = "javascript:DateCompare()";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlrbFromHalfday() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            this.rbFromHalfday = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "rbFromHalfday";
            @__ctrl.Text = "Half Day";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onclick", "javascript:ishalfday();");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnhalfday() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnhalfday = @__ctrl;
            @__ctrl.ID = "hdnhalfday";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControldateTimeEndDate() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.dateTimeEndDate = @__ctrl;
            @__ctrl.ID = "dateTimeEndDate";
            @__ctrl.DateOnly = true;
            @__ctrl.LocaleId = 1033;
            @__ctrl.OnValueChangeClientScript = "javascript:DateCompare()";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlrbToHalfday() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            this.rbToHalfday = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "rbToHalfday";
            @__ctrl.Text = "Half Day";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onclick", "javascript:istohalfday();");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlHalfDay() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnlHalfDay = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnlHalfDay";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                <span>\r\n                                    "));
            global::System.Web.UI.WebControls.CheckBox @__ctrl1;
            @__ctrl1 = this.@__BuildControlrbToHalfday();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</span>\r\n                            "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlSelecteddates() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.Selecteddates = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "row");
            @__ctrl.ID = "Selecteddates";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
            <div class=""col-md-6"">
                <div class=""form-group"">
                    <label for=""inputEmail"" class=""control-label col-xs-12  col-md-4"">From Date<span>(MM/DD/YYYY)</span></label>
                    <div class=""col-xs-12 col-md-8 halfdaycont"">
                        "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldateTimeStartDate();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div class=\"halfdaychk\">\r\n                            <" +
                        "span>\r\n                                "));
            global::System.Web.UI.WebControls.CheckBox @__ctrl2;
            @__ctrl2 = this.@__BuildControlrbFromHalfday();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</span>\r\n                            "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl3;
            @__ctrl3 = this.@__BuildControlhdnhalfday();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </div>
                    </div>
                </div>
            </div>
            <div class=""col-md-6"">
                <div class=""form-group"">
                    <label for=""inputEmail"" class=""control-label col-xs-12  col-md-4"">To Date<span>(MM/DD/YYYY)</span></label>
                    <div class=""col-xs-12 col-md-8 halfdaycont"">
                        "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl4;
            @__ctrl4 = this.@__BuildControldateTimeEndDate();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div class=\"halfdaychk\">\r\n                            "));
            global::System.Web.UI.WebControls.Panel @__ctrl5;
            @__ctrl5 = this.@__BuildControlpnlHalfDay();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n                    </div>\r\n                </d" +
                        "iv>\r\n            </div>\r\n        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControllstboxOptionalLeaves() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.lstboxOptionalLeaves = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.AutoPostBack = false;
            @__ctrl.ID = "lstboxOptionalLeaves";
            @__ctrl.CssClass = "optionalleavetype form-control";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "DateCompare()");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControloptinalDates() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.optinalDates = @__ctrl;
            @__ctrl.ID = "optinalDates";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "data double");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                            <label class=\"control-label  col-xs-4\">\r\n        " +
                        "                        Optional Leave</label>\r\n\r\n                            <d" +
                        "iv class=\"col-xs-12 col-md-8\">\r\n                                "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            @__ctrl1 = this.@__BuildControllstboxOptionalLeaves();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </div>\r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Panel @__BuildControlPnloptinalDates() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.PnloptinalDates = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "PnloptinalDates";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControloptinalDates();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblEmpID() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblEmpID = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblEmpID";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblDesgination() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblDesgination = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblDesgination";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblDepartment() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblDepartment = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblDepartment";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlTypeofLeave() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlTypeofLeave = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlTypeofLeave";
            @__ctrl.CssClass = "leavetype form-control";
            @__ctrl.AutoPostBack = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControllblDuration() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("label");
            this.lblDuration = @__ctrl;
            @__ctrl.ID = "lblDuration";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControltxtDuration() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.txtDuration = @__ctrl;
            @__ctrl.ID = "txtDuration";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtPurpose() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtPurpose = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtPurpose";
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.MultiLine;
            @__ctrl.CssClass = "form-control";
            @__ctrl.Rows = 6;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlddlReportingTo() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.ddlReportingTo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlReportingTo";
            @__ctrl.ReadOnly = true;
            @__ctrl.CssClass = "ReadOnly";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSubmit() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSubmit = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSubmit";
            @__ctrl.CssClass = "btn btn-md submit_btn";
            @__ctrl.Text = "Submit";
            @__ctrl.Click -= new System.EventHandler(this.BtnSubmitClick);
            @__ctrl.Click += new System.EventHandler(this.BtnSubmitClick);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnReset() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnReset = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnReset";
            @__ctrl.CssClass = "btn btn-md cancel_btn";
            @__ctrl.Text = "Reset";
            @__ctrl.Click -= new System.EventHandler(this.BtnResetClick);
            @__ctrl.Click += new System.EventHandler(this.BtnResetClick);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnCurrentUsername() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnCurrentUsername = @__ctrl;
            @__ctrl.ID = "hdnCurrentUsername";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnReportingTo() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnReportingTo = @__ctrl;
            @__ctrl.ID = "hdnReportingTo";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnCurrentYear() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnCurrentYear = @__ctrl;
            @__ctrl.ID = "hdnCurrentYear";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnEmployeeType() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnEmployeeType = @__ctrl;
            @__ctrl.ID = "hdnEmployeeType";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnHolidayList() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnHolidayList = @__ctrl;
            @__ctrl.ID = "hdnHolidayList";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnFnclStarts() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnFnclStarts = @__ctrl;
            @__ctrl.ID = "hdnFnclStarts";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnFnclEnds() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnFnclEnds = @__ctrl;
            @__ctrl.ID = "hdnFnclEnds";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblError() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblError = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblError";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.Font.Bold = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::LeaveApplication.LeaveRequestForm.LeaveRequestForm @__ctrl) {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlSelecteddates();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.Panel @__ctrl2;
            @__ctrl2 = this.@__BuildControlPnloptinalDates();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.Label @__ctrl3;
            @__ctrl3 = this.@__BuildControllblEmpID();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.Label @__ctrl4;
            @__ctrl4 = this.@__BuildControllblDesgination();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::System.Web.UI.WebControls.Label @__ctrl5;
            @__ctrl5 = this.@__BuildControllblDepartment();
            @__parser.AddParsedSubObject(@__ctrl5);
            global::System.Web.UI.WebControls.DropDownList @__ctrl6;
            @__ctrl6 = this.@__BuildControlddlTypeofLeave();
            @__parser.AddParsedSubObject(@__ctrl6);
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl7;
            @__ctrl7 = this.@__BuildControllblDuration();
            @__parser.AddParsedSubObject(@__ctrl7);
            global::System.Web.UI.WebControls.HiddenField @__ctrl8;
            @__ctrl8 = this.@__BuildControltxtDuration();
            @__parser.AddParsedSubObject(@__ctrl8);
            global::System.Web.UI.WebControls.TextBox @__ctrl9;
            @__ctrl9 = this.@__BuildControltxtPurpose();
            @__parser.AddParsedSubObject(@__ctrl9);
            global::System.Web.UI.WebControls.TextBox @__ctrl10;
            @__ctrl10 = this.@__BuildControlddlReportingTo();
            @__parser.AddParsedSubObject(@__ctrl10);
            global::System.Web.UI.WebControls.Button @__ctrl11;
            @__ctrl11 = this.@__BuildControlbtnSubmit();
            @__parser.AddParsedSubObject(@__ctrl11);
            global::System.Web.UI.WebControls.Button @__ctrl12;
            @__ctrl12 = this.@__BuildControlbtnReset();
            @__parser.AddParsedSubObject(@__ctrl12);
            global::System.Web.UI.WebControls.HiddenField @__ctrl13;
            @__ctrl13 = this.@__BuildControlhdnCurrentUsername();
            @__parser.AddParsedSubObject(@__ctrl13);
            global::System.Web.UI.WebControls.HiddenField @__ctrl14;
            @__ctrl14 = this.@__BuildControlhdnReportingTo();
            @__parser.AddParsedSubObject(@__ctrl14);
            global::System.Web.UI.WebControls.HiddenField @__ctrl15;
            @__ctrl15 = this.@__BuildControlhdnCurrentYear();
            @__parser.AddParsedSubObject(@__ctrl15);
            global::System.Web.UI.WebControls.HiddenField @__ctrl16;
            @__ctrl16 = this.@__BuildControlhdnEmployeeType();
            @__parser.AddParsedSubObject(@__ctrl16);
            global::System.Web.UI.WebControls.HiddenField @__ctrl17;
            @__ctrl17 = this.@__BuildControlhdnHolidayList();
            @__parser.AddParsedSubObject(@__ctrl17);
            global::System.Web.UI.WebControls.HiddenField @__ctrl18;
            @__ctrl18 = this.@__BuildControlhdnFnclStarts();
            @__parser.AddParsedSubObject(@__ctrl18);
            global::System.Web.UI.WebControls.HiddenField @__ctrl19;
            @__ctrl19 = this.@__BuildControlhdnFnclEnds();
            @__parser.AddParsedSubObject(@__ctrl19);
            global::System.Web.UI.WebControls.Label @__ctrl20;
            @__ctrl20 = this.@__BuildControllblError();
            @__parser.AddParsedSubObject(@__ctrl20);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write(@"
<script src=""../_layouts/15/LeaveApplication/jquery.min.js""></script>
<script src=""../_layouts/15/LeaveApplication/LeaveRequest.js""></script>
<script type=""text/javascript"" lang=""javascript "">

    function OnPickerFinish(resultfield) {
        clickDatePicker(null, """", """");
        DateCompare();

    }
    var durationValue = ""testvalue"";

    function DateCompare() {

        debugger;
        var jsondata = document.getElementById(""");
                                        @__w.Write( hdnHolidayList.ClientID );

            @__w.Write("\").value;\r\n        var leaveType = document.getElementById(\"");
                                         @__w.Write( ddlTypeofLeave.ClientID );

            @__w.Write("\");\r\n        var fromdate = document.getElementById(\"");
                                        @__w.Write( dateTimeStartDate.Controls[0].ClientID );

            @__w.Write("\").value;\r\n        var endDate = document.getElementById(\"");
                                       @__w.Write( dateTimeEndDate.Controls[0].ClientID );

            @__w.Write("\").value;\r\n        var optionalDates = document.getElementById(\"");
                                             @__w.Write( lstboxOptionalLeaves.ClientID );

            @__w.Write(@""");

        var obj = jQuery.parseJSON(jsondata);
        for (var i = 0; i < obj.length; i++) {
            if (fromdate == obj[i]) {
                alert(""Your Start Date comes under Company Holidays.Please Look at it."")
                break;
            }
            if (endDate == obj[i]) {
                alert(""Your End Date comes Under Company Holidays.Please Look at it."")
                break;
            }
        }
        var fValue = new Date(fromdate);
        var eValue = new Date(endDate);

        if (fromdate == endDate) {
            document.getElementById(""");
                             @__w.Write( pnlHalfDay.ClientID );

            @__w.Write("\").style.display = \'none\';\r\n        }\r\n        else\r\n            document.getElem" +
                    "entById(\"");
                             @__w.Write( pnlHalfDay.ClientID );

            @__w.Write(@""").style.display = 'block';
        var selectedLeave = leaveType.options[leaveType.selectedIndex].value;
        var tempfromdate = fValue;

        while (IsHoliday(tempfromdate, obj)) {
            tempfromdate.setDate(tempfromdate.getDate() + 1);
        }

        var tempenddate = eValue;

        while (IsHoliday(tempenddate, obj)) {
            tempenddate.setDate(tempenddate.getDate() - 1);
        }

        var leaveDays;
        leaveDays = DayDifference(tempfromdate, tempenddate);
        if (tempfromdate.toString() != tempenddate.toString()) {
            if (leaveDays > 0)
                leaveDays = leaveDays + 1;
            else
                leaveDays = 0;
        } else {
            leaveDays = 1;
        }

        var i;
        if (selectedLeave == ""Comp off"") {
            var countWorkingDays = 0;

            for (i = tempfromdate; tempfromdate.getTime() <= tempenddate.getTime() ; i.setDate(i.getDate() + 1)) {
                if (!IsHoliday(tempfromdate, obj))
                    countWorkingDays++;
            }
            if (countWorkingDays > 0) {
                document.getElementById(""");
                                 @__w.Write( lblDuration.ClientID );

            @__w.Write("\").innerText = countWorkingDays;\r\n                durationValue = countWorkingDay" +
                    "s;\r\n                document.getElementById(\"");
                                 @__w.Write( txtDuration.ClientID );

            @__w.Write("\").value = countWorkingDays;\r\n            }\r\n            else {\r\n                " +
                    "document.getElementById(\"");
                                 @__w.Write( lblDuration.ClientID );

            @__w.Write("\").innerText = 0;\r\n                durationValue = 0;\r\n                document.g" +
                    "etElementById(\"");
                                 @__w.Write( txtDuration.ClientID );

            @__w.Write(@""").value = 0;
            }
        }
        else if (selectedLeave == ""Optional"") {
            var leavesselected = 0;
            for (i = 0; i < optionalDates.options.length; i++) {
                var isSelected = optionalDates.options[i].selected;
                isSelected = (isSelected) ? ""selected"" : ""not selected"";

                if (isSelected == ""selected"")
                    leavesselected++;
            }
            document.getElementById(""");
                             @__w.Write( lblDuration.ClientID );

            @__w.Write("\").innerText = leavesselected;\r\n            durationValue = leavesselected;\r\n    " +
                    "        document.getElementById(\"");
                             @__w.Write( txtDuration.ClientID );

            @__w.Write("\").value = leavesselected;\r\n\r\n        } else {\r\n            document.getElementBy" +
                    "Id(\"");
                             @__w.Write( lblDuration.ClientID );

            @__w.Write("\").innerText = leaveDays;\r\n            durationValue = leaveDays;\r\n            do" +
                    "cument.getElementById(\"");
                             @__w.Write( txtDuration.ClientID );

            @__w.Write("\").value = leaveDays;\r\n        }\r\n\r\n    var durationdays = document.getElementByI" +
                    "d(\"");
                                        @__w.Write( txtDuration.ClientID );

            @__w.Write("\").value;\r\n\r\n        var isfromhalfday = document.getElementById(\"");
                                             @__w.Write( rbFromHalfday.ClientID );

            @__w.Write("\");\r\n        var istohalfday = document.getElementById(\"");
                                           @__w.Write( rbToHalfday.ClientID );

            @__w.Write("\");\r\n        if (isfromhalfday.checked) {\r\n\r\n            durationdays = parseFloa" +
                    "t(durationdays) - 0.5;\r\n            document.getElementById(\"");
                             @__w.Write( txtDuration.ClientID );

            @__w.Write("\").value = durationdays;\r\n            document.getElementById(\"");
                             @__w.Write( lblDuration.ClientID );

            @__w.Write("\").innerText = durationdays;\r\n\r\n        }\r\n        if (istohalfday.checked) {\r\n\r\n" +
                    "            durationdays = parseFloat(durationdays) - 0.5;\r\n            document" +
                    ".getElementById(\"");
                             @__w.Write( txtDuration.ClientID );

            @__w.Write("\").value = durationdays;\r\n            document.getElementById(\"");
                             @__w.Write( lblDuration.ClientID );

            @__w.Write(@""").innerText = durationdays;

        }
    }

    function DayDifference(tempfromdate, tempenddate) {
        var oneDay = 1000 * 60 * 60 * 24;

        var dayDiff = (Math.ceil((tempenddate.getTime() - tempfromdate.getTime()) / (oneDay)));

        return dayDiff;
    }

    function IsHoliday(fValue, jsondata) {
        var fdate = new Date(fValue);
        var tdate = fdate.getMonth() + 1 + ""/"" + fdate.getDate() + ""/"" + fdate.getFullYear();

        if (jsondata.toString().indexOf(tdate) != -1) {
            return true;
        }

        return IsSatOrSun(tdate);
    }

    function IsSatOrSun(fValue) {
        var tdate = new Date(fValue);

        if (tdate.getDay() == 0 || tdate.getDay() == 6) {
            return true;
        } else {
            return false;
        }
    }

    function ishalfday() {

        var durationdays = document.getElementById(""");
                                            @__w.Write( txtDuration.ClientID );

            @__w.Write("\").value;\r\n\r\n        var isfromhalfday = document.getElementById(\"");
                                             @__w.Write( rbFromHalfday.ClientID );

            @__w.Write("\");\r\n        var istohalfday = document.getElementById(\"");
                                           @__w.Write( rbToHalfday.ClientID );

            @__w.Write("\");\r\n        if (isfromhalfday.checked) {\r\n\r\n            durationdays = parseFloa" +
                    "t(durationdays) - 0.5;\r\n            document.getElementById(\"");
                             @__w.Write( txtDuration.ClientID );

            @__w.Write("\").value = durationdays;\r\n            document.getElementById(\"");
                             @__w.Write( lblDuration.ClientID );

            @__w.Write("\").innerText = durationdays;\r\n\r\n        }\r\n        else {\r\n            durationda" +
                    "ys = parseFloat(durationdays) + 0.5;\r\n            document.getElementById(\"");
                             @__w.Write( txtDuration.ClientID );

            @__w.Write("\").value = durationdays;\r\n            document.getElementById(\"");
                             @__w.Write( lblDuration.ClientID );

            @__w.Write("\").innerText = durationdays;\r\n        }\r\n\r\n    }\r\n\r\n    function istohalfday() {\r" +
                    "\n\r\n        var durationdays = document.getElementById(\"");
                                            @__w.Write( txtDuration.ClientID );

            @__w.Write("\").value;\r\n\r\n        var isfromhalfday = document.getElementById(\"");
                                             @__w.Write( rbFromHalfday.ClientID );

            @__w.Write("\");\r\n        var istohalfday = document.getElementById(\"");
                                           @__w.Write( rbToHalfday.ClientID );

            @__w.Write("\");\r\n        if (istohalfday.checked) {\r\n\r\n            durationdays = parseFloat(" +
                    "durationdays) - 0.5;\r\n            document.getElementById(\"");
                             @__w.Write( txtDuration.ClientID );

            @__w.Write("\").value = durationdays;\r\n            document.getElementById(\"");
                             @__w.Write( lblDuration.ClientID );

            @__w.Write("\").innerText = durationdays;\r\n        }\r\n        else {\r\n            durationdays" +
                    " = parseFloat(durationdays) + 0.5;\r\n            document.getElementById(\"");
                             @__w.Write( txtDuration.ClientID );

            @__w.Write("\").value = durationdays;\r\n            document.getElementById(\"");
                             @__w.Write( lblDuration.ClientID );

            @__w.Write("\").innerText = durationdays;\r\n            return;\r\n        }\r\n    }\r\n</script>\r\n\r" +
                    "\n<div class=\"whitbg leave_form\">\r\n    <h4>Leave Request Form</h4>\r\n    <div clas" +
                    "s=\"form-horizontal\">\r\n        ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n\r\n        <div class=\"row optleave\" style=\"display: none;\">\r\n            <div c" +
                    "lass=\"col-md-6\">\r\n                <div class=\"form-group\">\r\n                    " +
                    "");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write(@"
                </div>
            </div>
            <div class=""col-md-6"">
                <div class=""form-group daysoptionalleave"">
                </div>
            </div>
        </div>

        <div class=""row"">
            <div class=""col-md-6"" style=""display: none"">
                <div class=""form-group"">
                    <label class=""control-label col-xs-12  col-md-4"">
                        Employee Id</label>
                    <div class=""col-xs-12 col-md-8"">
                        ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write(@"
                    </div>
                </div>
                <div class=""form-group"">
                    <label class=""control-label col-xs-12  col-md-4"">
                        Designation</label>
                    <div class=""col-xs-12 col-md-8"">
                        ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write(@"
                    </div>
                </div>
            </div>
            <div class=""col-md-6"">
                <div class=""form-group"" style=""display: none"">
                    <label class=""control-label col-xs-12  col-md-4"">
                        Department</label>
                    <div class=""col-xs-12 col-md-8"">
                        ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write(@"
                    </div>
                </div>

                <div class=""form-group"">
                    <label class=""control-label col-xs-12  col-md-4"">
                        Type Of Leave</label>
                    <div class=""col-xs-12 col-md-8"">
                        ");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write(@"
                    </div>
                </div>
            </div>
            <div class=""col-md-6"">
                <div class=""form-group"">
                    <label class=""control-label col-xs-12  col-md-4"">
                        Duration</label>
                    <div class=""col-xs-12 col-md-8"">

                        ");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write("\r\n                        ");
            parameterContainer.Controls[7].RenderControl(@__w);
            @__w.Write(@"
                    </div>
                </div>
            </div>
        </div>

        <div class=""form-group"">
            <label for=""inputPassword"" class=""control-label col-md-2 col-sm-4 col-xs-4"">Purpose</label>
            <div class=""col-md-10 col-sm-8 col-xs-8"">
                ");
            parameterContainer.Controls[8].RenderControl(@__w);
            @__w.Write(@"
            </div>
        </div>

        <div class=""row"" style=""display: none"">
            <div class=""col-md-6"">
                <div class=""form-group"">
                    <label class=""control-label col-xs-12  col-md-4"">
                        Reporting To</label>
                    <div class=""col-xs-12 col-md-8"">
                        ");
            parameterContainer.Controls[9].RenderControl(@__w);
            @__w.Write("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
                    " </div>\r\n        <div class=\"row\">\r\n            <ul class=\"submit_cnt\">\r\n\r\n     " +
                    "           <li>\r\n                    ");
            parameterContainer.Controls[10].RenderControl(@__w);
            @__w.Write("</li>\r\n                <li>\r\n                    ");
            parameterContainer.Controls[11].RenderControl(@__w);
            @__w.Write("</li>\r\n            </ul>\r\n        </div>\r\n\r\n        <div class=\"row\">\r\n          " +
                    "  ");
            parameterContainer.Controls[12].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[13].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[14].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[15].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[16].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[17].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[18].RenderControl(@__w);
            @__w.Write("\r\n        </div>\r\n        <div class=\"row\">\r\n            ");
            parameterContainer.Controls[19].RenderControl(@__w);
            @__w.Write("\r\n        </div>\r\n    </div>\r\n</div>");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
