//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveApplication.Employee_Information_Forms.EmployeeInfoCreation {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class EmployeeInfoCreation {
        
        public static implicit operator global::System.Web.UI.TemplateControl(EmployeeInfoCreation target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::LeaveApplication.Employee_Information_Forms.EmployeeInfoCreation.EmployeeInfoCreation @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<html lang=\"en\">\r\n<head>\r\n    <link type=\"text/css\" rel=\"stylesheet\" href=\"\" " +
                        "/>\r\n    <link type=\"text/css\" rel=\"stylesheet\" href=\"\" />\r\n</head>\r\n<body>\r\n    " +
                        "<div class=\"container wrapper\">\r\n        <div class=\"row\">\r\n            <div cla" +
                        "ss=\"col-md-12\">\r\n                <div class=\"headerbg\">\r\n                    <h2" +
                        ">Employee Information Form</h2>\r\n                </div>\r\n            </div>\r\n   " +
                        "     </div>\r\n        <div class=\"row\">\r\n            <div class=\"compcont\">\r\n    " +
                        "            <div class=\"col-md-2 nopad\">\r\n                    <img src=\"images/l" +
                        "ogo.png\" class=\"img-responsive\" />\r\n                </div>\r\n                <div" +
                        " class=\"col-md-8\">\r\n                    <div class=\"companyinfo\">\r\n             " +
                        "           <ul>\r\n                            <li>Tillid Software Solutions Pvt. " +
                        "Ltd.</li>\r\n                            <li>Arut Jothi Towers (II floor),</li>\r\n " +
                        "                           <li>No: 2 &amp; 9, Shakthi Nagar,</li>\r\n             " +
                        "               <li>Mt. Poonamallee Rd,</li>\r\n                            <li>Por" +
                        "ur</li>\r\n                            <li>Chennai - 600 116.</li>\r\n              " +
                        "              <li><span>Phone</span>-<span>044 4505 2443</span><span> Wesbite : " +
                        "<a href=\"http://www.tillidsoftware.com/\" target=\"_blank\">http://www.tillidsoftwa" +
                        "re.com</a></span></li>\r\n                        </ul>\r\n                    </div" +
                        ">\r\n                </div>\r\n                <div class=\"col-md-2 nopad emp_image\"" +
                        ">\r\n                    <img src=\"images/placeholder.png\" class=\"img-responsive\" " +
                        "/>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div cla" +
                        "ss=\"row\">\r\n            <div class=\"col-md-12\">\r\n                <div class=\"inne" +
                        "rheadbg\">\r\n                    <h5>Personal Information</h5>\r\n                </" +
                        "div>\r\n            </div>\r\n        </div>\r\n        <div class=\"row\">\r\n           " +
                        " <div class=\"col-md-12\">\r\n                <div class=\"table-responsive personinf" +
                        "otable\">\r\n                    <table class=\"table tablenobrdr\">\r\n               " +
                        "         <tr>\r\n                            <td>First name</td>\r\n                " +
                        "            <td>\r\n                                <input type=\"text\" class=\"form" +
                        "-control\" />\r\n                            </td>\r\n                            <td" +
                        ">Last Name</td>\r\n                            <td>\r\n                             " +
                        "   <input type=\"text\" class=\"form-control\" />\r\n                            </td>" +
                        "\r\n                        </tr>\r\n                        <tr>\r\n                 " +
                        "           <td>Date of Birth</td>\r\n                            <td>\r\n           " +
                        "                     <input type=\"text\" class=\"form-control\" />\r\n               " +
                        "             </td>\r\n                            <td>Gender</td>\r\n               " +
                        "             <td>\r\n                                <label class=\"radio-inline\">\r" +
                        "\n                                    <input type=\"radio\" name=\"optradio\">Male</l" +
                        "abel>\r\n                                <label class=\"radio-inline\">\r\n           " +
                        "                         <input type=\"radio\" name=\"optradio\">Female</label>\r\n   " +
                        "                         </td>\r\n                        </tr>\r\n                 " +
                        "       <tr>\r\n                            <td>Present Address</td>\r\n             " +
                        "               <td colspan=\"3\">\r\n                                <textarea rows=" +
                        "\"6\" class=\"form-control\"></textarea>\r\n                            </td>\r\n       " +
                        "                 </tr>\r\n                        <tr>\r\n                          " +
                        "  <td>Permanent Address</td>\r\n                            <td colspan=\"3\">\r\n    " +
                        "                            <textarea rows=\"6\" class=\"form-control\"></textarea>\r" +
                        "\n                            </td>\r\n                        </tr>\r\n             " +
                        "           <tr>\r\n                            <td>Residence Contact No:</td>\r\n   " +
                        "                         <td colspan=\"3\">\r\n                                <tabl" +
                        "e width=\"100%\">\r\n                                    <tr>\r\n                     " +
                        "                   <td>\r\n                                            <input type" +
                        "=\"text\" class=\"form-control\" placeholder=\"Residence Contact Number 1\" /></td>\r\n " +
                        "                                       <td class=\"padclass\">\r\n                  " +
                        "                          <input type=\"text\" class=\"form-control\" placeholder=\"R" +
                        "esidence Contact Number 2\" /></td>\r\n                                        <td>" +
                        "Mobile No:</td>\r\n                                        <td>\r\n                 " +
                        "                           <input type=\"text\" class=\"form-control\" /></td>\r\n    " +
                        "                                </tr>\r\n                                </table>\r" +
                        "\n                            </td>\r\n                        </tr>\r\n             " +
                        "           <tr>\r\n                            <td>Martial Status:</td>\r\n         " +
                        "                   <td colspan=\"3\">\r\n                                <table widt" +
                        "h=\"100%\">\r\n                                    <tr>\r\n                           " +
                        "             <td colspan=\"2\">\r\n                                            <tabl" +
                        "e width=\"100%\">\r\n                                                <tr>\r\n         " +
                        "                                           <td>\r\n                               " +
                        "                         <label class=\"radio-inline\">\r\n                         " +
                        "                                   <input type=\"radio\" name=\"optradio\">Single</l" +
                        "abel>\r\n                                                        <label class=\"rad" +
                        "io-inline\">\r\n                                                            <input " +
                        "type=\"radio\" name=\"optradio\">Married</label>\r\n                                  " +
                        "                  </td>\r\n                                                    <td" +
                        ">Marriage Date</td>\r\n                                                </tr>\r\n    " +
                        "                                        </table>\r\n                              " +
                        "          </td>\r\n                                        <td colspan=\"2\">\r\n     " +
                        "                                       <table width=\"100%\">\r\n                   " +
                        "                             <tr>\r\n                                             " +
                        "       <td>\r\n                                                        <input type" +
                        "=\"text\" class=\"form-control\" />\r\n                                               " +
                        "     </td>\r\n                                                    <td class=\"padcl" +
                        "ass\">Kids (in numbers)</td>\r\n                                                   " +
                        " <td>\r\n                                                        <select class=\"fo" +
                        "rm-control\">\r\n                                                            <optio" +
                        "n>Select</option>\r\n                                                            <" +
                        "option value=\"1\">1</option>\r\n                                                   " +
                        "         <option value=\"2\">2</option>\r\n                                         " +
                        "                   <option value=\"3\">3</option>\r\n                               " +
                        "                             <option value=\"4\">4</option>\r\n                     " +
                        "                                   </select>\r\n                                  " +
                        "                  </td>\r\n                                                </tr>\r\n" +
                        "                                            </table>\r\n                          " +
                        "              </td>\r\n                                    </tr>\r\n                " +
                        "                </table>\r\n                            </td>\r\n                   " +
                        "     </tr>\r\n                    </table>\r\n                </div>\r\n            </" +
                        "div>\r\n        </div>\r\n        <div class=\"row\">\r\n            <div class=\"col-md-" +
                        "12\">\r\n                <div class=\"innerheadbg\">\r\n                    <h5>Family " +
                        "Details</h5>\r\n                </div>\r\n            </div>\r\n        </div>\r\n      " +
                        "  <div class=\"row\">\r\n            <div class=\"col-md-12\">\r\n                <div c" +
                        "lass=\"table-responsive customtab\">\r\n                    <table class=\"table\">\r\n " +
                        "                       <thead>\r\n                            <tr>\r\n              " +
                        "                  <th width=\"10%\">Sr No</th>\r\n                                <t" +
                        "h width=\"25%\">Name</th>\r\n                                <th width=\"15%\">Date of" +
                        " birth</th>\r\n                                <th width=\"10%\">Gender</th>\r\n      " +
                        "                          <th width=\"20%\">Relationship</th>\r\n                   " +
                        "             <th width=\"20%\">Occupation</th>\r\n                            </tr>\r" +
                        "\n                        </thead>\r\n                        <tbody>\r\n            " +
                        "                <tr>\r\n                                <td align=\"center\">1</td>\r" +
                        "\n                                <td>\r\n                                    <inpu" +
                        "t type=\"text\" class=\"form-control\"></td>\r\n                                <td>\r\n" +
                        "                                    <input type=\"text\" class=\"form-control\"></td" +
                        ">\r\n                                <td>\r\n                                    <in" +
                        "put type=\"text\" class=\"form-control\"></td>\r\n                                <td>" +
                        "\r\n                                    <input type=\"text\" class=\"form-control\"></" +
                        "td>\r\n                                <td>\r\n                                    <" +
                        "input type=\"text\" class=\"form-control\"></td>\r\n                            </tr>\r" +
                        "\n                            <tr>\r\n                                <td align=\"ce" +
                        "nter\">2</td>\r\n                                <td>\r\n                            " +
                        "        <input type=\"text\" class=\"form-control\"></td>\r\n                         " +
                        "       <td>\r\n                                    <input type=\"text\" class=\"form-" +
                        "control\"></td>\r\n                                <td>\r\n                          " +
                        "          <input type=\"text\" class=\"form-control\"></td>\r\n                       " +
                        "         <td>\r\n                                    <input type=\"text\" class=\"for" +
                        "m-control\"></td>\r\n                                <td>\r\n                        " +
                        "            <input type=\"text\" class=\"form-control\"></td>\r\n                     " +
                        "       </tr>\r\n                            <tr>\r\n                                " +
                        "<td align=\"center\">3</td>\r\n                                <td>\r\n               " +
                        "                     <input type=\"text\" class=\"form-control\"></td>\r\n            " +
                        "                    <td>\r\n                                    <input type=\"text\"" +
                        " class=\"form-control\"></td>\r\n                                <td>\r\n             " +
                        "                       <input type=\"text\" class=\"form-control\"></td>\r\n          " +
                        "                      <td>\r\n                                    <input type=\"tex" +
                        "t\" class=\"form-control\"></td>\r\n                                <td>\r\n           " +
                        "                         <input type=\"text\" class=\"form-control\"></td>\r\n        " +
                        "                    </tr>\r\n                            <tr>\r\n                   " +
                        "             <td align=\"center\">4</td>\r\n                                <td>\r\n  " +
                        "                                  <input type=\"text\" class=\"form-control\"></td>\r" +
                        "\n                                <td>\r\n                                    <inpu" +
                        "t type=\"text\" class=\"form-control\"></td>\r\n                                <td>\r\n" +
                        "                                    <input type=\"text\" class=\"form-control\"></td" +
                        ">\r\n                                <td>\r\n                                    <in" +
                        "put type=\"text\" class=\"form-control\"></td>\r\n                                <td>" +
                        "\r\n                                    <input type=\"text\" class=\"form-control\"></" +
                        "td>\r\n                            </tr>\r\n                            <tr>\r\n      " +
                        "                          <td align=\"center\">5</td>\r\n                           " +
                        "     <td>\r\n                                    <input type=\"text\" class=\"form-co" +
                        "ntrol\"></td>\r\n                                <td>\r\n                            " +
                        "        <input type=\"text\" class=\"form-control\"></td>\r\n                         " +
                        "       <td>\r\n                                    <input type=\"text\" class=\"form-" +
                        "control\"></td>\r\n                                <td>\r\n                          " +
                        "          <input type=\"text\" class=\"form-control\"></td>\r\n                       " +
                        "         <td>\r\n                                    <input type=\"text\" class=\"for" +
                        "m-control\"></td>\r\n                            </tr>\r\n                        </t" +
                        "body>\r\n                    </table>\r\n                </div>\r\n            </div>\r" +
                        "\n        </div>\r\n        <div class=\"row\">\r\n            <div class=\"col-md-12\">\r" +
                        "\n                <div class=\"innerheadbg\">\r\n                    <h5>Medical Cond" +
                        "ition</h5>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        " +
                        "<div class=\"row\">\r\n            <div class=\"col-md-12\">\r\n                <div cla" +
                        "ss=\"table-responsive customtab\">\r\n                    <table class=\"table\">\r\n   " +
                        "                     <tr>\r\n                            <td width=\"30%\">Blood Gro" +
                        "up</td>\r\n                            <td width=\"70%\"></td>\r\n                    " +
                        "    </tr>\r\n                        <tr>\r\n                            <td width=\"" +
                        "30%\">Ailments (Heart condition, BP, Sugar, etc.,)</td>\r\n                        " +
                        "    <td width=\"70%\"></td>\r\n                        </tr>\r\n                      " +
                        "  <tr>\r\n                            <td width=\"30%\">Allergies (Drug, food, etc.," +
                        ")</td>\r\n                            <td width=\"70%\"></td>\r\n                     " +
                        "   </tr>\r\n                        <tr>\r\n                            <td width=\"3" +
                        "0%\">Undergoing any other medications?</td>\r\n                            <td widt" +
                        "h=\"70%\"></td>\r\n                        </tr>\r\n                    </table>\r\n    " +
                        "            </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"row\"" +
                        ">\r\n            <div class=\"col-md-12\">\r\n                <div class=\"innerheadbg\"" +
                        ">\r\n                    <h5>Emergency Contact Details</h5>\r\n                </div" +
                        ">\r\n            </div>\r\n        </div>\r\n        <div class=\"row\">\r\n            <d" +
                        "iv class=\"col-md-12\">\r\n                <div class=\"table-responsive customtab\">\r" +
                        "\n                    <table class=\"table\">\r\n                        <thead>\r\n   " +
                        "                         <tr>\r\n                                <th width=\"10%\">S" +
                        "r No</th>\r\n                                <th width=\"25%\">Contact Person Name</" +
                        "th>\r\n                                <th width=\"35%\">Relation</th>\r\n            " +
                        "                    <th width=\"15%\">Landline No</th>\r\n                          " +
                        "      <th width=\"15%\">Mobile No</th>\r\n                            </tr>\r\n       " +
                        "                 </thead>\r\n                        <tbody>\r\n                    " +
                        "        <tr>\r\n                                <td align=\"center\">1</td>\r\n       " +
                        "                         <td>\r\n                                    <input type=\"" +
                        "text\" class=\"form-control\"></td>\r\n                                <td>\r\n        " +
                        "                            <input type=\"text\" class=\"form-control\"></td>\r\n     " +
                        "                           <td>\r\n                                    <input type" +
                        "=\"text\" class=\"form-control\"></td>\r\n                                <td>\r\n      " +
                        "                              <input type=\"text\" class=\"form-control\"></td>\r\n   " +
                        "                         </tr>\r\n                            <tr>\r\n              " +
                        "                  <td align=\"center\">2</td>\r\n                                <td" +
                        ">\r\n                                    <input type=\"text\" class=\"form-control\"><" +
                        "/td>\r\n                                <td>\r\n                                    " +
                        "<input type=\"text\" class=\"form-control\"></td>\r\n                                <" +
                        "td>\r\n                                    <input type=\"text\" class=\"form-control\"" +
                        "></td>\r\n                                <td>\r\n                                  " +
                        "  <input type=\"text\" class=\"form-control\"></td>\r\n                            </t" +
                        "r>\r\n                            <tr>\r\n                                <td align=" +
                        "\"center\">3</td>\r\n                                <td>\r\n                         " +
                        "           <input type=\"text\" class=\"form-control\"></td>\r\n                      " +
                        "          <td>\r\n                                    <input type=\"text\" class=\"fo" +
                        "rm-control\"></td>\r\n                                <td>\r\n                       " +
                        "             <input type=\"text\" class=\"form-control\"></td>\r\n                    " +
                        "            <td>\r\n                                    <input type=\"text\" class=\"" +
                        "form-control\"></td>\r\n                            </tr>\r\n                        " +
                        "    <tr>\r\n                                <td align=\"center\">4</td>\r\n           " +
                        "                     <td>\r\n                                    <input type=\"text" +
                        "\" class=\"form-control\"></td>\r\n                                <td>\r\n            " +
                        "                        <input type=\"text\" class=\"form-control\"></td>\r\n         " +
                        "                       <td>\r\n                                    <input type=\"te" +
                        "xt\" class=\"form-control\"></td>\r\n                                <td>\r\n          " +
                        "                          <input type=\"text\" class=\"form-control\"></td>\r\n       " +
                        "                     </tr>\r\n                            <tr>\r\n                  " +
                        "              <td align=\"center\">5</td>\r\n                                <td>\r\n " +
                        "                                   <input type=\"text\" class=\"form-control\"></td>" +
                        "\r\n                                <td>\r\n                                    <inp" +
                        "ut type=\"text\" class=\"form-control\"></td>\r\n                                <td>\r" +
                        "\n                                    <input type=\"text\" class=\"form-control\"></t" +
                        "d>\r\n                                <td>\r\n                                    <i" +
                        "nput type=\"text\" class=\"form-control\"></td>\r\n                            </tr>\r\n" +
                        "                        </tbody>\r\n                    </table>\r\n                " +
                        "</div>\r\n            </div>\r\n        </div>\r\n        <div class=\"row\">\r\n         " +
                        "   <div class=\"col-md-12\">\r\n                <div class=\"innerheadbg\">\r\n         " +
                        "           <h5>Educational Qualification</h5>\r\n                </div>\r\n         " +
                        "   </div>\r\n        </div>\r\n        <div class=\"row\">\r\n            <div class=\"co" +
                        "l-md-12\">\r\n                <div class=\"table-responsive customtab\">\r\n           " +
                        "         <table class=\"table\">\r\n                        <thead>\r\n               " +
                        "             <tr>\r\n                                <th width=\"10%\">Sr No</th>\r\n " +
                        "                               <th width=\"25%\">School/Degree/Diploma/Certificate" +
                        "</th>\r\n                                <th width=\"25%\">Institute/University</th>" +
                        "\r\n                                <th width=\"15%\">From</th>\r\n                   " +
                        "             <th width=\"15%\">To</th>\r\n                                <th width=" +
                        "\"10%\">Percentage</th>\r\n                            </tr>\r\n                      " +
                        "  </thead>\r\n                        <tbody>\r\n                            <tr>\r\n " +
                        "                               <td align=\"center\">1</td>\r\n                      " +
                        "          <td>\r\n                                    <input type=\"text\" class=\"fo" +
                        "rm-control\"></td>\r\n                                <td>\r\n                       " +
                        "             <input type=\"text\" class=\"form-control\"></td>\r\n                    " +
                        "            <td>\r\n                                    <input type=\"text\" class=\"" +
                        "form-control\"></td>\r\n                                <td>\r\n                     " +
                        "               <input type=\"text\" class=\"form-control\"></td>\r\n                  " +
                        "              <td>\r\n                                    <input type=\"text\" class" +
                        "=\"form-control\"></td>\r\n                            </tr>\r\n                      " +
                        "      <tr>\r\n                                <td align=\"center\">2</td>\r\n         " +
                        "                       <td>\r\n                                    <input type=\"te" +
                        "xt\" class=\"form-control\"></td>\r\n                                <td>\r\n          " +
                        "                          <input type=\"text\" class=\"form-control\"></td>\r\n       " +
                        "                         <td>\r\n                                    <input type=\"" +
                        "text\" class=\"form-control\"></td>\r\n                                <td>\r\n        " +
                        "                            <input type=\"text\" class=\"form-control\"></td>\r\n     " +
                        "                           <td>\r\n                                    <input type" +
                        "=\"text\" class=\"form-control\"></td>\r\n                            </tr>\r\n         " +
                        "                   <tr>\r\n                                <td align=\"center\">3</t" +
                        "d>\r\n                                <td>\r\n                                    <i" +
                        "nput type=\"text\" class=\"form-control\"></td>\r\n                                <td" +
                        ">\r\n                                    <input type=\"text\" class=\"form-control\"><" +
                        "/td>\r\n                                <td>\r\n                                    " +
                        "<input type=\"text\" class=\"form-control\"></td>\r\n                                <" +
                        "td>\r\n                                    <input type=\"text\" class=\"form-control\"" +
                        "></td>\r\n                                <td>\r\n                                  " +
                        "  <input type=\"text\" class=\"form-control\"></td>\r\n                            </t" +
                        "r>\r\n                            <tr>\r\n                                <td align=" +
                        "\"center\">4</td>\r\n                                <td>\r\n                         " +
                        "           <input type=\"text\" class=\"form-control\"></td>\r\n                      " +
                        "          <td>\r\n                                    <input type=\"text\" class=\"fo" +
                        "rm-control\"></td>\r\n                                <td>\r\n                       " +
                        "             <input type=\"text\" class=\"form-control\"></td>\r\n                    " +
                        "            <td>\r\n                                    <input type=\"text\" class=\"" +
                        "form-control\"></td>\r\n                                <td>\r\n                     " +
                        "               <input type=\"text\" class=\"form-control\"></td>\r\n                  " +
                        "          </tr>\r\n                            <tr>\r\n                             " +
                        "   <td align=\"center\">5</td>\r\n                                <td>\r\n            " +
                        "                        <input type=\"text\" class=\"form-control\"></td>\r\n         " +
                        "                       <td>\r\n                                    <input type=\"te" +
                        "xt\" class=\"form-control\"></td>\r\n                                <td>\r\n          " +
                        "                          <input type=\"text\" class=\"form-control\"></td>\r\n       " +
                        "                         <td>\r\n                                    <input type=\"" +
                        "text\" class=\"form-control\"></td>\r\n                                <td>\r\n        " +
                        "                            <input type=\"text\" class=\"form-control\"></td>\r\n     " +
                        "                       </tr>\r\n                        </tbody>\r\n                " +
                        "    </table>\r\n                </div>\r\n            </div>\r\n        </div>\r\n      " +
                        "  <div class=\"row\">\r\n            <div class=\"col-md-12\">\r\n                <div c" +
                        "lass=\"innerheadbg\">\r\n                    <h5>Other Dossier</h5>\r\n               " +
                        " </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"row\">\r\n        " +
                        "    <div class=\"col-md-12\">\r\n                <div class=\"table-responsive custom" +
                        "tab\">\r\n                    <table class=\"table\">\r\n                        <tr>\r\n" +
                        "                            <td width=\"20%\">Aadhar Card Number:</td>\r\n          " +
                        "                  <td width=\"80%\"></td>\r\n                        </tr>\r\n        " +
                        "                <tr>\r\n                            <td width=\"20%\">PAN Card Numbe" +
                        "r:</td>\r\n                            <td width=\"80%\"></td>\r\n                    " +
                        "    </tr>\r\n                        <tr>\r\n                            <td width=\"" +
                        "20%\">Passport Number :</td>\r\n                            <td width=\"80%\"></td>\r\n" +
                        "                        </tr>\r\n                        <tr>\r\n                   " +
                        "         <td width=\"20%\">Bank A/C No you want your salary to be credited (if fro" +
                        "m HDFC) with Branch Name :</td>\r\n                            <td width=\"80%\"></t" +
                        "d>\r\n                        </tr>\r\n                        <tr>\r\n               " +
                        "             <td width=\"20%\">PF A/C No :</td>\r\n                            <td w" +
                        "idth=\"80%\"></td>\r\n                        </tr>\r\n                        <tr>\r\n " +
                        "                           <td width=\"20%\">UAN No :</td>\r\n                      " +
                        "      <td width=\"80%\"></td>\r\n                        </tr>\r\n                    " +
                        "    <tr>\r\n                            <td width=\"20%\">ESIC No :</td>\r\n          " +
                        "                  <td width=\"80%\"></td>\r\n                        </tr>\r\n        " +
                        "                <tr>\r\n                            <td width=\"20%\">Mode of Transp" +
                        "ort – Vehicle No :</td>\r\n                            <td width=\"80%\">\r\n         " +
                        "                       <table width=\"100%\" class=\"innertable\">\r\n                " +
                        "                    <tr>\r\n                                        <td>Two wheele" +
                        "r</td>\r\n                                        <td>\r\n                          " +
                        "                  <input type=\"text\" class=\"form-control\" /></td>\r\n             " +
                        "                           <td class=\"padclass\">Four Wheeler</td>\r\n             " +
                        "                           <td>\r\n                                            <in" +
                        "put type=\"text\" class=\"form-control\" /></td>\r\n                                  " +
                        "      <td class=\"padclass\">Public Transport</td>\r\n                              " +
                        "          <td>\r\n                                            <input type=\"text\" c" +
                        "lass=\"form-control\" /></td>\r\n                                    </tr>\r\n        " +
                        "                        </table>\r\n                            </td>\r\n           " +
                        "             </tr>\r\n                    </table>\r\n                </div>\r\n      " +
                        "      </div>\r\n        </div>\r\n        <div class=\"row\">\r\n            <div class=" +
                        "\"col-md-12\">\r\n                <div class=\"innerheadbg\">\r\n                    <h5" +
                        ">References (other than family members)</h5>\r\n                </div>\r\n          " +
                        "  </div>\r\n        </div>\r\n        <div class=\"row\">\r\n            <div class=\"col" +
                        "-md-12\">\r\n                <div class=\"table-responsive customtab\">\r\n            " +
                        "        <table class=\"table\">\r\n                        <thead>\r\n                " +
                        "            <tr>\r\n                                <th width=\"10%\">Sr No</th>\r\n  " +
                        "                              <th width=\"20%\">Name</th>\r\n                       " +
                        "         <th width=\"27%\">Working In</th>\r\n                                <th wi" +
                        "dth=\"27%\">Working As</th>\r\n                                <th width=\"16%\">Conta" +
                        "ct No</th>\r\n                            </tr>\r\n                        </thead>\r" +
                        "\n                        <tbody>\r\n                            <tr>\r\n            " +
                        "                    <td align=\"center\">1</td>\r\n                                <" +
                        "td>\r\n                                    <input type=\"text\" class=\"form-control\"" +
                        "></td>\r\n                                <td>\r\n                                  " +
                        "  <input type=\"text\" class=\"form-control\"></td>\r\n                               " +
                        " <td>\r\n                                    <input type=\"text\" class=\"form-contro" +
                        "l\"></td>\r\n                                <td>\r\n                                " +
                        "    <input type=\"text\" class=\"form-control\"></td>\r\n                            <" +
                        "/tr>\r\n                            <tr>\r\n                                <td alig" +
                        "n=\"center\">2</td>\r\n                                <td>\r\n                       " +
                        "             <input type=\"text\" class=\"form-control\"></td>\r\n                    " +
                        "            <td>\r\n                                    <input type=\"text\" class=\"" +
                        "form-control\"></td>\r\n                                <td>\r\n                     " +
                        "               <input type=\"text\" class=\"form-control\"></td>\r\n                  " +
                        "              <td>\r\n                                    <input type=\"text\" class" +
                        "=\"form-control\"></td>\r\n                            </tr>\r\n                      " +
                        "      <tr>\r\n                                <td align=\"center\">3</td>\r\n         " +
                        "                       <td>\r\n                                    <input type=\"te" +
                        "xt\" class=\"form-control\"></td>\r\n                                <td>\r\n          " +
                        "                          <input type=\"text\" class=\"form-control\"></td>\r\n       " +
                        "                         <td>\r\n                                    <input type=\"" +
                        "text\" class=\"form-control\"></td>\r\n                                <td>\r\n        " +
                        "                            <input type=\"text\" class=\"form-control\"></td>\r\n     " +
                        "                       </tr>\r\n                            <tr>\r\n                " +
                        "                <td align=\"center\">4</td>\r\n                                <td>\r" +
                        "\n                                    <input type=\"text\" class=\"form-control\"></t" +
                        "d>\r\n                                <td>\r\n                                    <i" +
                        "nput type=\"text\" class=\"form-control\"></td>\r\n                                <td" +
                        ">\r\n                                    <input type=\"text\" class=\"form-control\"><" +
                        "/td>\r\n                                <td>\r\n                                    " +
                        "<input type=\"text\" class=\"form-control\"></td>\r\n                            </tr>" +
                        "\r\n                            <tr>\r\n                                <td align=\"c" +
                        "enter\">5</td>\r\n                                <td>\r\n                           " +
                        "         <input type=\"text\" class=\"form-control\"></td>\r\n                        " +
                        "        <td>\r\n                                    <input type=\"text\" class=\"form" +
                        "-control\"></td>\r\n                                <td>\r\n                         " +
                        "           <input type=\"text\" class=\"form-control\"></td>\r\n                      " +
                        "          <td>\r\n                                    <input type=\"text\" class=\"fo" +
                        "rm-control\"></td>\r\n                            </tr>\r\n                        </" +
                        "tbody>\r\n                    </table>\r\n                </div>\r\n            </div>" +
                        "\r\n        </div>\r\n        <div class=\"row\">\r\n            <div class=\"col-md-12\">" +
                        "\r\n                <div class=\"innerheadbg\">\r\n                    <h5>Previous Ex" +
                        "perience(s)</h5>\r\n                </div>\r\n            </div>\r\n        </div>\r\n  " +
                        "      <div class=\"row\">\r\n            <div class=\"col-md-12\">\r\n                <d" +
                        "iv class=\"table-responsive customtab\">\r\n                    <table class=\"table\"" +
                        ">\r\n                        <thead>\r\n                            <tr>\r\n          " +
                        "                      <th width=\"5%\">Sr No</th>\r\n                               " +
                        " <th width=\"15%\">Company Name</th>\r\n                                <th width=\"1" +
                        "5%\">Designation</th>\r\n                                <th width=\"15%\">Date Of Jo" +
                        "ining</th>\r\n                                <th width=\"15%\">Date Of Relieving</t" +
                        "h>\r\n                                <th width=\"15%\">Contact No</th>\r\n           " +
                        "                     <th width=\"20%\">Reason</th>\r\n                            </" +
                        "tr>\r\n                        </thead>\r\n                        <tbody>\r\n        " +
                        "                    <tr>\r\n                                <td align=\"center\">1</" +
                        "td>\r\n                                <td>\r\n                                    <" +
                        "input type=\"text\" class=\"form-control\"></td>\r\n                                <t" +
                        "d>\r\n                                    <input type=\"text\" class=\"form-control\">" +
                        "</td>\r\n                                <td>\r\n                                   " +
                        " <input type=\"text\" class=\"form-control\"></td>\r\n                                " +
                        "<td>\r\n                                    <input type=\"text\" class=\"form-control" +
                        "\"></td>\r\n                                <td>\r\n                                 " +
                        "   <input type=\"text\" class=\"form-control\"></td>\r\n                              " +
                        "  <td>\r\n                                    <input type=\"text\" class=\"form-contr" +
                        "ol\"></td>\r\n                            </tr>\r\n                            <tr>\r\n" +
                        "                                <td align=\"center\">2</td>\r\n                     " +
                        "           <td>\r\n                                    <input type=\"text\" class=\"f" +
                        "orm-control\"></td>\r\n                                <td>\r\n                      " +
                        "              <input type=\"text\" class=\"form-control\"></td>\r\n                   " +
                        "             <td>\r\n                                    <input type=\"text\" class=" +
                        "\"form-control\"></td>\r\n                                <td>\r\n                    " +
                        "                <input type=\"text\" class=\"form-control\"></td>\r\n                 " +
                        "               <td>\r\n                                    <input type=\"text\" clas" +
                        "s=\"form-control\"></td>\r\n                                <td>\r\n                  " +
                        "                  <input type=\"text\" class=\"form-control\"></td>\r\n               " +
                        "             </tr>\r\n                            <tr>\r\n                          " +
                        "      <td align=\"center\">3</td>\r\n                                <td>\r\n         " +
                        "                           <input type=\"text\" class=\"form-control\"></td>\r\n      " +
                        "                          <td>\r\n                                    <input type=" +
                        "\"text\" class=\"form-control\"></td>\r\n                                <td>\r\n       " +
                        "                             <input type=\"text\" class=\"form-control\"></td>\r\n    " +
                        "                            <td>\r\n                                    <input typ" +
                        "e=\"text\" class=\"form-control\"></td>\r\n                                <td>\r\n     " +
                        "                               <input type=\"text\" class=\"form-control\"></td>\r\n  " +
                        "                              <td>\r\n                                    <input t" +
                        "ype=\"text\" class=\"form-control\"></td>\r\n                            </tr>\r\n      " +
                        "                      <tr>\r\n                                <td align=\"center\">4" +
                        "</td>\r\n                                <td>\r\n                                   " +
                        " <input type=\"text\" class=\"form-control\"></td>\r\n                                " +
                        "<td>\r\n                                    <input type=\"text\" class=\"form-control" +
                        "\"></td>\r\n                                <td>\r\n                                 " +
                        "   <input type=\"text\" class=\"form-control\"></td>\r\n                              " +
                        "  <td>\r\n                                    <input type=\"text\" class=\"form-contr" +
                        "ol\"></td>\r\n                                <td>\r\n                               " +
                        "     <input type=\"text\" class=\"form-control\"></td>\r\n                            " +
                        "    <td>\r\n                                    <input type=\"text\" class=\"form-con" +
                        "trol\"></td>\r\n                            </tr>\r\n                            <tr>" +
                        "\r\n                                <td align=\"center\">5</td>\r\n                   " +
                        "             <td>\r\n                                    <input type=\"text\" class=" +
                        "\"form-control\"></td>\r\n                                <td>\r\n                    " +
                        "                <input type=\"text\" class=\"form-control\"></td>\r\n                 " +
                        "               <td>\r\n                                    <input type=\"text\" clas" +
                        "s=\"form-control\"></td>\r\n                                <td>\r\n                  " +
                        "                  <input type=\"text\" class=\"form-control\"></td>\r\n               " +
                        "                 <td>\r\n                                    <input type=\"text\" cl" +
                        "ass=\"form-control\"></td>\r\n                                <td>\r\n                " +
                        "                    <input type=\"text\" class=\"form-control\"></td>\r\n             " +
                        "               </tr>\r\n                        </tbody>\r\n                    </ta" +
                        "ble>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div c" +
                        "lass=\"row\">\r\n            <div class=\"col-md-12\">\r\n                <p>I hereby af" +
                        "firm that the aforementioned information given by me is true and correct and tha" +
                        "t I have not held back any information. Any information given here is found to b" +
                        "e false, I shall be liable for dismissal.</p>\r\n                <div class=\"decal" +
                        "ration\">\r\n                    <p>This is to acknowledge that Tillid Software Sol" +
                        "utions does not hold any of my original documents.  And the company no longer re" +
                        "sponsible for the same in case of any loss.</p>\r\n                </div>\r\n       " +
                        "         <p class=\"redtxt\">* In case any changes in personal information should " +
                        "be intimate to HR department within 24 hrs.</p>\r\n            </div>\r\n        </d" +
                        "iv>\r\n        <div class=\"row\">\r\n            <div class=\"col-md-12\">\r\n           " +
                        "     <div class=\"table-responsive customtab\">\r\n                    <table class=" +
                        "\"table\">\r\n                        <tr>\r\n                            <td width=\"3" +
                        "0%\">Date:</td>\r\n                            <td width=\"70%\"></td>\r\n             " +
                        "           </tr>\r\n                        <tr>\r\n                            <td " +
                        "width=\"30%\">Place:</td>\r\n                            <td width=\"70%\"></td>\r\n    " +
                        "                    </tr>\r\n                        <tr>\r\n                       " +
                        "     <td colspan=\"2\" align=\"right\">\r\n                                <p>Sudhakar" +
                        " KT</p>\r\n                                <p><strong>Siganture</strong></p>\r\n    " +
                        "                        </td>\r\n                        </tr>\r\n                  " +
                        "  </table>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </di" +
                        "v>\r\n</body>\r\n</html>"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
