//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveApplication.NewWebparts.Edit_EmployeeInformation {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class Edit_EmployeeInformation {
        
        protected global::System.Web.UI.WebControls.Label lblrr;
        
        protected global::System.Web.UI.WebControls.Label lb1;
        
        protected global::System.Web.UI.WebControls.TextBox txtempid;
        
        protected global::System.Web.UI.WebControls.Label Label1;
        
        protected global::System.Web.UI.WebControls.TextBox txtempusername;
        
        protected global::System.Web.UI.WebControls.Label Label2;
        
        protected global::System.Web.UI.WebControls.TextBox txtfristname;
        
        protected global::System.Web.UI.WebControls.Label Label3;
        
        protected global::System.Web.UI.WebControls.TextBox txtlastname;
        
        protected global::System.Web.UI.WebControls.Label Label4;
        
        protected global::System.Web.UI.WebControls.DropDownList DdlEmptype;
        
        protected global::System.Web.UI.WebControls.Label Label5;
        
        protected global::System.Web.UI.WebControls.DropDownList DdlDep;
        
        protected global::System.Web.UI.WebControls.Label Label6;
        
        protected global::System.Web.UI.WebControls.DropDownList DdlDesignation;
        
        protected global::System.Web.UI.WebControls.Label Label7;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlReportingTo;
        
        protected global::System.Web.UI.WebControls.Label Label8;
        
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl DtDoj;
        
        protected global::System.Web.UI.WebControls.Label Label9;
        
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl DtDOP;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divdop;
        
        protected global::System.Web.UI.WebControls.CheckBox chkPrePL;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divCFPL;
        
        protected global::System.Web.UI.WebControls.Label LblError;
        
        protected global::System.Web.UI.WebControls.Button BtnRegister;
        
        protected global::System.Web.UI.WebControls.Button BtnCancel;
        
        protected global::System.Web.UI.WebControls.HiddenField empSPid;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnCurrentYear;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnCurrentEmpType;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnStrtFnclMnth;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnCurrentUsername;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnCurrentManager;
        
        protected global::System.Web.UI.WebControls.HiddenField hdncurrentEmployee;
        
        public static implicit operator global::System.Web.UI.TemplateControl(Edit_EmployeeInformation target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblrr() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblrr = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblrr";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllb1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lb1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lb1";
            @__ctrl.Text = "*";
            @__ctrl.CssClass = "validspan";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtempid() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtempid = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtempid";
            @__ctrl.ReadOnly = true;
            @__ctrl.CssClass = "ReadOnly form-control";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label1";
            @__ctrl.Text = "*";
            @__ctrl.CssClass = "validspan";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtempusername() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtempusername = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtempusername";
            @__ctrl.ReadOnly = true;
            @__ctrl.CssClass = "ReadOnly form-control";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel2() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label2";
            @__ctrl.Text = "*";
            @__ctrl.CssClass = "validspan";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtfristname() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtfristname = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtfristname";
            @__ctrl.CssClass = "form-control";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel3() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label3";
            @__ctrl.Text = "*";
            @__ctrl.CssClass = "validspan";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtlastname() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtlastname = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtlastname";
            @__ctrl.CssClass = "form-control";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel4() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label4 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label4";
            @__ctrl.Text = "*";
            @__ctrl.CssClass = "validspan";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDdlEmptype() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.DdlEmptype = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "DdlEmptype";
            @__ctrl.AutoPostBack = false;
            @__ctrl.CssClass = "form-control";
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.DdlEmptype_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.DdlEmptype_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel5() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label5 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label5";
            @__ctrl.Text = "*";
            @__ctrl.CssClass = "validspan";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDdlDep() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.DdlDep = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "DdlDep";
            @__ctrl.AutoPostBack = false;
            @__ctrl.CssClass = "form-control";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel6() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label6 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label6";
            @__ctrl.Text = "*";
            @__ctrl.CssClass = "validspan";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDdlDesignation() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.DdlDesignation = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "DdlDesignation";
            @__ctrl.AutoPostBack = false;
            @__ctrl.CssClass = "form-control";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel7() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label7 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label7";
            @__ctrl.Text = "*";
            @__ctrl.CssClass = "validspan";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlReportingTo() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlReportingTo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlReportingTo";
            @__ctrl.AutoPostBack = true;
            @__ctrl.CssClass = "form-control";
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.DdlReportingToSelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.DdlReportingToSelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel8() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label8 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label8";
            @__ctrl.Text = "*";
            @__ctrl.CssClass = "validspan";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlDtDoj() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.DtDoj = @__ctrl;
            @__ctrl.ID = "DtDoj";
            @__ctrl.DateOnly = true;
            @__ctrl.LocaleId = 1033;
            @__ctrl.CssClassTextBox = "form-control";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel9() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label9 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label9";
            @__ctrl.Text = "*";
            @__ctrl.CssClass = "validspan";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlDtDOP() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.DtDOP = @__ctrl;
            @__ctrl.ID = "DtDOP";
            @__ctrl.DateOnly = true;
            @__ctrl.LocaleId = 1033;
            @__ctrl.CssClassTextBox = "form-control";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivdop() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divdop = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-group caldcont");
            @__ctrl.ID = "divdop";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            <label class=\"control-label col-xs-4  col-md-4\">\r\n                D" +
                        "ate of Permanent (MM/DD/YYYY)"));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControlLabel9();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            </label>\r\n            \r\n            <div class=\"col-xs-8  col-md-8\"" +
                        ">\r\n                "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl2;
            @__ctrl2 = this.@__BuildControlDtDOP();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            </div>\r\n        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlchkPrePL() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            this.chkPrePL = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "chkPrePL";
            @__ctrl.CssClass = "form-control";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivCFPL() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divCFPL = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-group");
            @__ctrl.ID = "divCFPL";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            <label class=\"control-label col-xs-4  col-md-4\">Carry forward PL\'s<" +
                        "/label>\r\n            <div class=\"col-xs-8  col-md-8\">\r\n                "));
            global::System.Web.UI.WebControls.CheckBox @__ctrl1;
            @__ctrl1 = this.@__BuildControlchkPrePL();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            </div>\r\n        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLblError() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.LblError = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "LblError";
            @__ctrl.CssClass = "ErrorInfo";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnRegister() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.BtnRegister = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Text = "Submit";
            @__ctrl.ID = "BtnRegister";
            @__ctrl.CssClass = "btn btn-md submit_btn";
            @__ctrl.ValidationGroup = "save";
            @__ctrl.Click -= new System.EventHandler(this.BtnUpdateClick);
            @__ctrl.Click += new System.EventHandler(this.BtnUpdateClick);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnCancel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.BtnCancel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Text = "Close";
            @__ctrl.ID = "BtnCancel";
            @__ctrl.CssClass = "btn btn-md cancel_btn";
            @__ctrl.Click -= new System.EventHandler(this.BtnCancelClick);
            @__ctrl.Click += new System.EventHandler(this.BtnCancelClick);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlempSPid() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.empSPid = @__ctrl;
            @__ctrl.ID = "empSPid";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnCurrentYear() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnCurrentYear = @__ctrl;
            @__ctrl.ID = "hdnCurrentYear";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnCurrentEmpType() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnCurrentEmpType = @__ctrl;
            @__ctrl.ID = "hdnCurrentEmpType";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnStrtFnclMnth() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnStrtFnclMnth = @__ctrl;
            @__ctrl.ID = "hdnStrtFnclMnth";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnCurrentUsername() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnCurrentUsername = @__ctrl;
            @__ctrl.ID = "hdnCurrentUsername";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnCurrentManager() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnCurrentManager = @__ctrl;
            @__ctrl.ID = "hdnCurrentManager";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdncurrentEmployee() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdncurrentEmployee = @__ctrl;
            @__ctrl.ID = "hdncurrentEmployee";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::LeaveApplication.NewWebparts.Edit_EmployeeInformation.Edit_EmployeeInformation @__ctrl) {
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllblrr();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControllb1();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            @__ctrl3 = this.@__BuildControltxtempid();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.Label @__ctrl4;
            @__ctrl4 = this.@__BuildControlLabel1();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::System.Web.UI.WebControls.TextBox @__ctrl5;
            @__ctrl5 = this.@__BuildControltxtempusername();
            @__parser.AddParsedSubObject(@__ctrl5);
            global::System.Web.UI.WebControls.Label @__ctrl6;
            @__ctrl6 = this.@__BuildControlLabel2();
            @__parser.AddParsedSubObject(@__ctrl6);
            global::System.Web.UI.WebControls.TextBox @__ctrl7;
            @__ctrl7 = this.@__BuildControltxtfristname();
            @__parser.AddParsedSubObject(@__ctrl7);
            global::System.Web.UI.WebControls.Label @__ctrl8;
            @__ctrl8 = this.@__BuildControlLabel3();
            @__parser.AddParsedSubObject(@__ctrl8);
            global::System.Web.UI.WebControls.TextBox @__ctrl9;
            @__ctrl9 = this.@__BuildControltxtlastname();
            @__parser.AddParsedSubObject(@__ctrl9);
            global::System.Web.UI.WebControls.Label @__ctrl10;
            @__ctrl10 = this.@__BuildControlLabel4();
            @__parser.AddParsedSubObject(@__ctrl10);
            global::System.Web.UI.WebControls.DropDownList @__ctrl11;
            @__ctrl11 = this.@__BuildControlDdlEmptype();
            @__parser.AddParsedSubObject(@__ctrl11);
            global::System.Web.UI.WebControls.Label @__ctrl12;
            @__ctrl12 = this.@__BuildControlLabel5();
            @__parser.AddParsedSubObject(@__ctrl12);
            global::System.Web.UI.WebControls.DropDownList @__ctrl13;
            @__ctrl13 = this.@__BuildControlDdlDep();
            @__parser.AddParsedSubObject(@__ctrl13);
            global::System.Web.UI.WebControls.Label @__ctrl14;
            @__ctrl14 = this.@__BuildControlLabel6();
            @__parser.AddParsedSubObject(@__ctrl14);
            global::System.Web.UI.WebControls.DropDownList @__ctrl15;
            @__ctrl15 = this.@__BuildControlDdlDesignation();
            @__parser.AddParsedSubObject(@__ctrl15);
            global::System.Web.UI.WebControls.Label @__ctrl16;
            @__ctrl16 = this.@__BuildControlLabel7();
            @__parser.AddParsedSubObject(@__ctrl16);
            global::System.Web.UI.WebControls.DropDownList @__ctrl17;
            @__ctrl17 = this.@__BuildControlddlReportingTo();
            @__parser.AddParsedSubObject(@__ctrl17);
            global::System.Web.UI.WebControls.Label @__ctrl18;
            @__ctrl18 = this.@__BuildControlLabel8();
            @__parser.AddParsedSubObject(@__ctrl18);
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl19;
            @__ctrl19 = this.@__BuildControlDtDoj();
            @__parser.AddParsedSubObject(@__ctrl19);
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl20;
            @__ctrl20 = this.@__BuildControldivdop();
            @__parser.AddParsedSubObject(@__ctrl20);
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl21;
            @__ctrl21 = this.@__BuildControldivCFPL();
            @__parser.AddParsedSubObject(@__ctrl21);
            global::System.Web.UI.WebControls.Label @__ctrl22;
            @__ctrl22 = this.@__BuildControlLblError();
            @__parser.AddParsedSubObject(@__ctrl22);
            global::System.Web.UI.WebControls.Button @__ctrl23;
            @__ctrl23 = this.@__BuildControlBtnRegister();
            @__parser.AddParsedSubObject(@__ctrl23);
            global::System.Web.UI.WebControls.Button @__ctrl24;
            @__ctrl24 = this.@__BuildControlBtnCancel();
            @__parser.AddParsedSubObject(@__ctrl24);
            global::System.Web.UI.WebControls.HiddenField @__ctrl25;
            @__ctrl25 = this.@__BuildControlempSPid();
            @__parser.AddParsedSubObject(@__ctrl25);
            global::System.Web.UI.WebControls.HiddenField @__ctrl26;
            @__ctrl26 = this.@__BuildControlhdnCurrentYear();
            @__parser.AddParsedSubObject(@__ctrl26);
            global::System.Web.UI.WebControls.HiddenField @__ctrl27;
            @__ctrl27 = this.@__BuildControlhdnCurrentEmpType();
            @__parser.AddParsedSubObject(@__ctrl27);
            global::System.Web.UI.WebControls.HiddenField @__ctrl28;
            @__ctrl28 = this.@__BuildControlhdnStrtFnclMnth();
            @__parser.AddParsedSubObject(@__ctrl28);
            global::System.Web.UI.WebControls.HiddenField @__ctrl29;
            @__ctrl29 = this.@__BuildControlhdnCurrentUsername();
            @__parser.AddParsedSubObject(@__ctrl29);
            global::System.Web.UI.WebControls.HiddenField @__ctrl30;
            @__ctrl30 = this.@__BuildControlhdnCurrentManager();
            @__parser.AddParsedSubObject(@__ctrl30);
            global::System.Web.UI.WebControls.HiddenField @__ctrl31;
            @__ctrl31 = this.@__BuildControlhdncurrentEmployee();
            @__parser.AddParsedSubObject(@__ctrl31);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n\r\n<script lang=\"javascript\" type=\"text/javascript\">\r\n    $(document).ready(func" +
                    "tion () {\r\n        hideOrVisibleDivdop($.trim($(\'#");
                               @__w.Write( DdlEmptype.ClientID );

            @__w.Write("\').val()));\r\n        $(\'#");
    @__w.Write( DdlEmptype.ClientID );

            @__w.Write("\').change(function () {\r\n            hideOrVisibleDivdop($.trim($(this).val()));\r" +
                    "\n        });\r\n        function hideOrVisibleDivdop(selectedValue) {\r\n           " +
                    " if (selectedValue == \"Permanent\") {\r\n                $(\'#");
            @__w.Write( divdop.ClientID );

            @__w.Write("\').show();\r\n                $(\'#");
            @__w.Write( divCFPL.ClientID );

            @__w.Write("\').show();\r\n            } else {\r\n                $(\'#");
            @__w.Write( divdop.ClientID );

            @__w.Write("\').hide();\r\n                $(\'#");
            @__w.Write( divCFPL.ClientID );

            @__w.Write(@"').hide();
            }
        }
    });
</script>

<div class=""whitbg leave_form"">
    <h3>Please enter the following details.</h3>
    <div class=""form-horizontal"">
        <div class=""form-group"">
            <label class=""control-label col-xs-4  col-md-4"">Employee Id");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("</label>\r\n            \r\n            <div class=\"col-xs-8  col-md-8\">\r\n           " +
                    "     ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n         " +
                    "   <label class=\"control-label col-xs-4  col-md-4\">Employee Name");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("</label>\r\n            \r\n            <div class=\"col-xs-8  col-md-8\">\r\n           " +
                    "     ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n         " +
                    "   <label class=\"control-label col-xs-4  col-md-4\">First Name");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write("</label>\r\n            \r\n            <div class=\"col-xs-8  col-md-8\">\r\n           " +
                    "     ");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n         " +
                    "   <label class=\"control-label col-xs-4  col-md-4\">Last Name");
            parameterContainer.Controls[7].RenderControl(@__w);
            @__w.Write("</label>\r\n            \r\n            <div class=\"col-xs-8  col-md-8\">\r\n           " +
                    "     ");
            parameterContainer.Controls[8].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n         " +
                    "   <label class=\"control-label col-xs-4  col-md-4\">Employee Type");
            parameterContainer.Controls[9].RenderControl(@__w);
            @__w.Write("</label>\r\n            \r\n            <div class=\"col-xs-8  col-md-8\">\r\n           " +
                    "     ");
            parameterContainer.Controls[10].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n         " +
                    "   <label class=\"control-label col-xs-4  col-md-4\">Department");
            parameterContainer.Controls[11].RenderControl(@__w);
            @__w.Write("</label>\r\n            \r\n            <div class=\"col-xs-8  col-md-8\">\r\n           " +
                    "     ");
            parameterContainer.Controls[12].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n         " +
                    "   <label class=\"control-label col-xs-4  col-md-4\">Designation");
            parameterContainer.Controls[13].RenderControl(@__w);
            @__w.Write("</label>\r\n            \r\n            <div class=\"col-xs-8  col-md-8\">\r\n           " +
                    "     ");
            parameterContainer.Controls[14].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n         " +
                    "   <label class=\"control-label col-xs-4  col-md-4\">Reporting To");
            parameterContainer.Controls[15].RenderControl(@__w);
            @__w.Write("</label>\r\n            \r\n            <div class=\"col-xs-8  col-md-8\">\r\n           " +
                    "     ");
            parameterContainer.Controls[16].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n        </div>\r\n        <div class=\"form-group caldcont\">\r\n" +
                    "            <label class=\"control-label col-xs-4  col-md-4\">\r\n                Da" +
                    "te of Join (MM/DD/YYYY)");
            parameterContainer.Controls[17].RenderControl(@__w);
            @__w.Write("\r\n            </label>\r\n            \r\n            <div class=\"col-xs-8  col-md-8\"" +
                    ">\r\n\r\n                ");
            parameterContainer.Controls[18].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n        </div>\r\n        ");
            parameterContainer.Controls[19].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[20].RenderControl(@__w);
            @__w.Write("\r\n        <div class=\"form-group error-label\">\r\n            ");
               if (!string.IsNullOrEmpty(LblError.Text.Trim()))
               {
            parameterContainer.Controls[21].RenderControl(@__w);
            @__w.Write("\r\n            ");
               } 
            @__w.Write("\r\n        </div>\r\n        <div class=\"row\">\r\n            <ul class=\"submit_cnt\">\r" +
                    "\n                <li>\r\n                    ");
            parameterContainer.Controls[22].RenderControl(@__w);
            @__w.Write("\r\n                </li>\r\n                <li>\r\n                    ");
            parameterContainer.Controls[23].RenderControl(@__w);
            @__w.Write("\r\n                </li>\r\n            </ul>\r\n        </div>\r\n        ");
            parameterContainer.Controls[24].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[25].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[26].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[27].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[28].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[29].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[30].RenderControl(@__w);
            @__w.Write("\r\n    </div>\r\n</div>\r\n\r\n\r\n\r\n");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
