//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveApplication.EmployeeLeaveStatus {
    using System.Web.UI.WebControls.Expressions;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebControls;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Data;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Configuration;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    
    
    public partial class EmployeeLeaveStatus {
        
        protected global::System.Web.UI.WebControls.Button BtnApprove;
        
        protected global::System.Web.UI.WebControls.Button BtnReject;
        
        protected global::System.Web.UI.WebControls.Label lblErr;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnCurrentYear;
        
        public static implicit operator global::System.Web.UI.TemplateControl(EmployeeLeaveStatus target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnApprove() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.BtnApprove = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Text = "Approve";
            @__ctrl.ID = "BtnApprove";
            @__ctrl.CssClass = "btn btn-md submit_btn";
            @__ctrl.Click -= new System.EventHandler(this.BtnApproveClick);
            @__ctrl.Click += new System.EventHandler(this.BtnApproveClick);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnReject() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.BtnReject = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Text = "Reject";
            @__ctrl.ID = "BtnReject";
            @__ctrl.CssClass = "btn btn-md cancel_btn";
            @__ctrl.Click -= new System.EventHandler(this.BtnRejectClick);
            @__ctrl.Click += new System.EventHandler(this.BtnRejectClick);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblErr() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblErr = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblErr";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnCurrentYear() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnCurrentYear = @__ctrl;
            @__ctrl.ID = "hdnCurrentYear";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::LeaveApplication.EmployeeLeaveStatus.EmployeeLeaveStatus @__ctrl) {
            global::System.Web.UI.WebControls.Button @__ctrl1;
            @__ctrl1 = this.@__BuildControlBtnApprove();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.Button @__ctrl2;
            @__ctrl2 = this.@__BuildControlBtnReject();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.Label @__ctrl3;
            @__ctrl3 = this.@__BuildControllblErr();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.HiddenField @__ctrl4;
            @__ctrl4 = this.@__BuildControlhdnCurrentYear();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n<script src=\"../_layouts/15/LeaveApplication/LeaveStatus.js\"></script>\r\n");
   DataTable results = (DataTable)ViewState["Results"];
   if (results != null && results.Rows.Count > 0)
   {

            @__w.Write(@"
<div class=""Container1 empleavestatus"">

    <div class=""table-responsive"">
        <table class=""table header"">
            <tr class=""header"">
                <th colspan=""9"" style=""border-top: 1px solid #FFF; border-left: 1px solid #FFF; border-right: 1px solid #FFF; padding: 0px;"">
                    <h4 class=""font"">Leave Requests</h4>
                </th>
            </tr>
            <tr class=""header font"">
                <th width=""2%"" align=""center"">
                    <input type=""checkbox"" onclick=""checkAll(this);"">
                </th>
                <th class=""font"" width=""17%"">Requested From
                </th>
                <th class=""font"" width=""10%"">Leave Type
                </th>
                <th class=""font"" width=""5%"">Start Date
                </th>
                <th class=""font"" width=""5%"">End Date
                </th>
                <th class=""font"" width=""5%"">Duration
                </th>
                <th class=""font"" width=""20%"">Reason
                </th>
                <th class=""font"" width=""6%"">Status
                </th>
                <th class=""font"" width=""30%"">Remarks
                </th>
            </tr>

            ");
               foreach (DataRow dataRow in results.Rows)
               {
            
            @__w.Write("\r\n            <tr>\r\n                <td>\r\n                    <input type=\"checkb" +
                    "ox\" onclick=\"Check_Click(this);\" name=\'");
                                                                      @__w.Write( "Chk" + dataRow["Id"].ToString() );

            @__w.Write("\' />\r\n                </td>\r\n                <td>\r\n                    ");
            @__w.Write( dataRow["RequestedFrom"].ToString() );

            @__w.Write("\r\n                </td>\r\n                <td>\r\n                    ");
            @__w.Write( dataRow["Leave Type"].ToString());

            @__w.Write("\r\n                </td>\r\n                <td>\r\n                    ");
            @__w.Write( dataRow["Starting Date"].ToString());

            @__w.Write("\r\n                </td>\r\n                <td>\r\n                    ");
            @__w.Write( dataRow["Ending Date"].ToString());

            @__w.Write("\r\n                </td>\r\n                <td>\r\n                    ");
            @__w.Write( dataRow["Duration"].ToString());

            @__w.Write("\r\n                </td>\r\n                <td>\r\n                    <div>\r\n       " +
                    "                 ");
                @__w.Write( dataRow["Reason"].ToString());

            @__w.Write("\r\n                    </div>\r\n                </td>\r\n                <td>\r\n      " +
                    "              ");
                      if (dataRow["Status"].ToString().Trim() == "Pending")
                      {
            @__w.Write("\r\n                    <div style=\"color: #e84743\">\r\n                        ");
                @__w.Write( dataRow["Status"].ToString());

            @__w.Write("\r\n                    </div>\r\n                    ");
                       }
                      else
                      { 
            @__w.Write("\r\n                    <div>\r\n                        ");
                @__w.Write( dataRow["Status"].ToString());

            @__w.Write("\r\n                    </div>\r\n                    ");
                       }
            @__w.Write("\r\n                </td>\r\n                <td>\r\n                    <input type=\"t" +
                    "ext\" class=\"form-control\" name=\'");
                                                          @__w.Write( "txt" + dataRow["Id"].ToString() );

            @__w.Write("\'\r\n                        id=\'");
                    @__w.Write( "txt" + dataRow["Id"].ToString() );

            @__w.Write("\' />\r\n                </td>\r\n            </tr>\r\n            ");
              } 
            @__w.Write("\r\n        </table>\r\n        <ul class=\"submit_cnt mtop-15 mright-0\">\r\n           " +
                    " <li>\r\n                ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("</li>\r\n            <li>\r\n                ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("</li>\r\n        </ul>\r\n        ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n    </div>\r\n</div>\r\n");
   }
   else
   { 
            @__w.Write(@"
<div class=""Container1 empleavestatus"">
    <div class=""table-responsive"">
        <table class=""table"">
            <tr>
                <th>There is no pending leave requests to approve.
                </th>
            </tr>
        </table>
    </div>
</div>
");
   } 
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
